# Generated by Django 5.0.6 on 2026-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryFailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
