export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const SAVE_SHIPPING_ADDRESS='SAVE_SHIPPING_ADDRESS'

export const SAVE_PAYMENT_METHOD='SAVE_PAYMENT_METHOD'
export const CART_CLEAR_ITEM='CART_CLEAR_ITEM'

export const USER_ADDRESS_LIST_REQUEST = 'USER_ADDRESS_LIST_REQUEST'
export const USER_ADDRESS_LIST_SUCCESS = 'USER_ADDRESS_LIST_SUCCESS'
export const USER_ADDRESS_LIST_FAIL = 'USER_ADDRESS_LIST_FAIL'
export const USER_ADDRESS_LIST_RESET = 'USER_ADDRESS_LIST_RESET'

export const USER_ADDRESS_ADD_REQUEST = 'USER_ADDRESS_ADD_REQUEST'
export const USER_ADDRESS_ADD_SUCCESS = 'USER_ADDRESS_ADD_SUCCESS'
export const USER_ADDRESS_ADD_FAIL = 'USER_ADDRESS_ADD_FAIL'
export const USER_ADDRESS_ADD_RESET = 'USER_ADDRESS_ADD_RESET'

export const USER_ADDRESS_DELETE_REQUEST = 'USER_ADDRESS_DELETE_REQUEST'
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS'
export const USER_ADDRESS_DELETE_FAIL = 'USER_ADDRESS_DELETE_FAIL'
export const USER_ADDRESS_DELETE_RESET = 'USER_ADDRESS_DELETE_RESET'

export const USER_ADDRESS_UPDATE_REQUEST = 'USER_ADDRESS_UPDATE_REQUEST'
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS'
export const USER_ADDRESS_UPDATE_FAIL = 'USER_ADDRESS_UPDATE_FAIL'
export const USER_ADDRESS_UPDATE_RESET = 'USER_ADDRESS_UPDATE_RESET'
